version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        environment:
            - APP_NAME=${APP_NAME}
            - APP_ENV=${APP_ENV}
            - APP_KEY=${APP_KEY}
            - APP_DEBUG=${APP_DEBUG}
            - APP_URL=${APP_URL}
            - DB_CONNECTION=${DB_CONNECTION}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - SESSION_DRIVER=${SESSION_DRIVER}
            - SESSION_DOMAIN=${SESSION_DOMAIN}
            - SESSION_SECURE_COOKIE=${SESSION_SECURE_COOKIE}
            - FILESYSTEM_DISK=${FILESYSTEM_DISK}
            - WABLAS_API_KEY=${WABLAS_API_KEY}
            - WABLAS_URL=${WABLAS_URL}
            - VITE_APP_NAME=${VITE_APP_NAME}
            - VITE_API_URL=${VITE_API_URL}
        depends_on:
            - web

    web:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf # Sesuaikan path jika berbeda
        depends_on:
            - app
